language: python

python:
  - "2.7"

# whitelist branches
branches:
  only:
    - staging

# command to install dependencies, e.g. pip install -r
# Install tox for testing neutron builds.
install: pip install tox

# command to run tests, e.g. python setup.py test
# Running neutron unit tests for python
script: 
    - tox -v -e pep8
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then travis_wait tox -v -e py27 -- --parallel --concurrency=1 neutron.tests.unit; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then travis_wait tox -v -e py34 -- --parallel --concurrency=1 neutron.tests.unit; fi
